name: Bulk Issue Creater
on:
  workflow_dispatch:
    inputs:
      repos_list:
        description: "List of repositories in the format 'x', 'y', 'z'..."
        type: string
        required: true
      issue_title: 
        description: "Issue title (Repo name will be appended before this title)"
        type: string
        required: true
      issue_body:
        description: "Issue body message"
        type: string
        default: ""
      issue_assignee:
        description: "Assignee for all the issues (should've write access to the repo)"
        type: string
        default: "usamasadiq"
      issue_label:
        description: "Label to identify the created issues"
        type: string
        default: "Django 4.2 Upgrade"

jobs:
  repos_list:
    name: Parse repos list
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.repos_list.outputs.list }}
    steps:
    - name: get repos list
      id: repos_list
      run: |
        echo "::set-output name=list::[${{github.event.inputs.repos_list}}]"

  create_bulk_issues:
    name: Create Bulk Issues
    runs-on: ubuntu-20.04
    needs: [ repos_list ]
    permissions:
      issues: write
    strategy:
      fail-fast: false
      matrix:
        repos: ${{fromJson(needs.repos_list.outputs.output1)}}

    steps:
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "${{ github.event.inputs.issue_assignee }}"
          labels: "${{ github.event.inputs.issue_label }}"
          title: "[${{ matrix.repos }}]: ${{github.event.inputs.issue_title}}"
          body: "${{ github.event.inputs.issue_body }}"

        env:
          GITHUB_TOKEN: ${{ secrets.requirements_bot_github_token }}
