name: Bulk Issue Creater
on:
  workflow_dispatch:
    inputs:
      repos_list:
        description: "List of repositories in the format 'x', 'y', 'z'..."
        type: string
        required: true
      issue_title: 
        description: "Issue title (Repo name will be appended before this title)"
        type: string
        required: true
      issue_body:
        description: "Issue body message"
        type: string
        default: ""

jobs:
  repos_list:
    name: Parse repos list
    runs-on: ubuntu-20.04
    outputs:
      output1: ${{ steps.repos_list.outputs.list }}
    steps:
    - name: get repos list
      id: repos_list
      run: |
        echo "::set-output name=list::[${{github.event.inputs.repos_list}}]"

  create_bulk_issues:
    name: Create Bulk Issues
    runs-on: ubuntu-20.04
    needs: [ repos_list ]
    permissions:
      issues: write
    strategy:
      fail-fast: false
      matrix:
        repos: ${{fromJson(needs.repos_list.outputs.output1)}}

    steps:
      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "usamasadiq"
          labels: "Django 4.2 Upgrade"
          title: "[${{ matrix.repos }}]: ${{github.event.inputs.issue_title}}"
          body: |
            ## Description
            Follow and Complete all of the following steps for the issue to be marked as done.

            - [ ] Update tox & Github action workflow using modernisers to add support for Django 4.2
            - [ ] Remove any versions of Python earlier than 3.8 from tox.ini, .travis.yml, and GitHub Actions workflows.
            - [ ] Update the trove classifiers in setup.py, setup.cfg or pyproject.toml files.
            - [ ] Run and verify all tests are passing in the CI for Django 4.2
            - [ ] Run available code-mods to fix the failing tests
            - [ ] Add CHANGELOG entry with description "Support added for Django 4.2"
            - [ ] Bump the package version and release a new version on GitHub & PyPI (whichever is applicable)
            - [ ] Update the repo support field in the Dependency Upgrade Sheet. 

        env:
          GITHUB_TOKEN: ${{ secrets.requirements_bot_github_token }}
